### ISSUE TITLE
Ошибка при загрузке выписки по кредитной карте

### ISSUE THREAD

**Issue by avkoch** [another1Cstuff/ClientRaiffeisenbank#1]
Добрый день,

Пользуюсь обработкой с модифицированной конфигурацией из https://chtch.ru/ru/1sdengi/

Версия платформы: 8.3.22.1709
Версия конфигурации: 2.0.44.28

При запросе номеров счетов отображаются все кроме номера счёта кредитной карты.

При попытке загрузить выписку получаю сообщение:
```
ОШИБКА. Не найден счет операции по 7 последним цифрам XXXXXXX
{ВнешняяОбработка.КлиентРайффайзенбанк.МодульОбъекта(0)}:
{Обработка.ЗагрузкаВыпискиБанка.Форма.ЗагрузкаВыписки.Форма(3196)}:ТаблицаРезультат = ОбработкаКлиентБанк.ПолучитьВыписку(КонтекстВыполнения);
{Обработка.ЗагрузкаВыпискиБанка.Форма.ЗагрузкаВыписки.Форма(627)}:ЗагрузитьКлиентБанкСервер();
```

где XXXXXXX последние цифры номера счёта кредитной карты.

**Comment by another1Cstuff** [comment]
https://github.com/another1Cstuff/Client-1C-Money-Raiffeisenbank/releases/tag/v5.99.72.4
